# Generated by Django 5.1.1 on 2024-09-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-binary'), ('Q', 'Genderqueer'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=2)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=50)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('po_box_number', models.IntegerField(default=0)),
                ('emergency_phone_number', models.CharField(max_length=10)),
                ('passport_number', models.CharField(max_length=50)),
                ('visa_documents', models.FileField(null=True, upload_to='uploads/')),
                ('departure_city', models.CharField(blank=True, max_length=50)),
                ('destination_city', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
